# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.CharField(max_length=50, unique=True)),
                ('answer_question', models.CharField(max_length=200)),
                ('answer_before', models.CharField(max_length=200)),
                ('answer_after', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_id', models.CharField(max_length=50, unique=True)),
                ('diary_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('diary_skill', models.CharField(max_length=50)),
                ('diary_title', models.CharField(max_length=200)),
                ('diary_detail', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(max_length=50, unique=True)),
                ('feedback_start_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('feedback_end_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('feedback_state', models.CharField(choices=[('INI', 'Initial State'), ('DIARY', 'Diary State'), ('FIN', 'Final State')], default='INI', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=50, unique=True)),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_id', models.CharField(max_length=50, unique=True)),
                ('questionnaire_text', models.CharField(max_length=200)),
                ('questionnaire_start_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(max_length=50, unique=True)),
                ('study_field', models.CharField(max_length=50)),
                ('study_owner', models.CharField(max_length=50)),
                ('study_start_date', models.DateTimeField(verbose_name='date published')),
                ('study_questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=50)),
                ('user_start_date', models.DateTimeField(verbose_name='date published')),
                ('user_end_date', models.DateTimeField(verbose_name='date finished')),
                ('user_feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Feedback')),
                ('user_study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Study')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Questionnaire'),
        ),
        migrations.AddField(
            model_name='diary',
            name='diary_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Feedback'),
        ),
    ]
