# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='questionnaire_field',
            field=models.CharField(default=models.CharField(max_length=200), max_length=50),
        ),
    ]
