# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_questionnaire_questionnaire_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire_field',
            field=models.CharField(max_length=50),
        ),
    ]
