# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170729_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_field',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
