# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170731_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInfo',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='diary_user',
            new_name='diary_userInfo',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_email',
            new_name='userInfo_email',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_end_date',
            new_name='userInfo_end_date',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_feedback',
            new_name='userInfo_feedback',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_id',
            new_name='userInfo_id',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_name',
            new_name='userInfo_name',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_start_date',
            new_name='userInfo_start_date',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_study',
            new_name='userInfo_study',
        ),
    ]
