# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170805_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
