# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170805_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire_field',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userInfo_feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Feedback'),
        ),
    ]
