# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170813_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_id', models.CharField(max_length=50, unique=True)),
                ('diary_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
