# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='diary_id',
            new_name='skill_id',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='diary_name',
            new_name='skill_name',
        ),
    ]
