# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20170817_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='diary_latitude',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='diary',
            name='diary_longitude',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
