# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20170820_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userInfo_email',
            field=models.EmailField(max_length=254),
        ),
    ]
