# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20170824_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='study_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='study_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date end'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_start_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
