# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 08:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20170915_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_active',
            field=models.BooleanField(default=False, verbose_name='Active Study?'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_start_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Study Date Published'),
        ),
    ]
