# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20170915_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='study_active',
        ),
        migrations.AddField(
            model_name='study',
            name='is_study_active',
            field=models.BooleanField(default=False, verbose_name='Active Study? - all the other study will set to false if active this study'),
        ),
    ]
